apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-pipeline-sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/niharbabu99/sample-application
    targetRevision: main
    path: ci/*
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

