apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-pipeline-sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io
    chart: niharbabu99/pr-pipeline-chart                      
    targetRevision: 1.0.0                         
    helm:
      values: |
        {{- (index (fromYaml (get (httpGet "https://raw.githubusercontent.com/niharbabu99/sample-application/main/helm-values/values.yaml")))) | toYaml }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

