apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-pipeline-sample-app-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: niharbabu99/pr-pipeline-chart
    repoURL: https://github.com/niharbabu99/sample-application.git
    targetRevision: main
    helm:
      valueFiles:
        - ci/helm-values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

