apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-pipeline-sample-app-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: niharbabu99/pr-pipeline-chart
    repoURL: ghcr.io
    targetRevision: 1.0.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

